const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')
const { loadQmlJs } = require('./load-qml-js.cjs')

const parsers = loadQmlJs(path.join(__dirname, '..', 'parsers', 'SystemParsers.js'))
const fixture = name => fs.readFileSync(path.join(__dirname, 'fixtures', name), 'utf8')
const failed = result => assert.equal(result.ok, false)

test('parses aggregate /proc/stat counters and excludes guest counters from total', () => {
  const result = parsers.parseProcStat(fixture('proc-stat-valid.txt'))
  assert.equal(result.ok, true)
  assert.equal(result.data.idleTotal, 64482)
  assert.equal(result.data.total, 71465)
  failed(parsers.parseProcStat('cpu 1 2 nope 4\n'))
  failed(parsers.parseProcStat('cpu 1 2 3\n'))
  failed(parsers.parseProcStat('cpu -1 2 3 4\n'))
})

test('parses memory, supports no configured swap, and rejects impossible or truncated values', () => {
  const result = parsers.parseMeminfo(fixture('meminfo-valid.txt'))
  assert.equal(result.ok, true)
  assert.equal(result.data.used, 8388608000)
  assert.equal(result.data.swapUsed, 1073739776)
  const noSwap = parsers.parseMeminfo('MemTotal: 10 kB\nMemAvailable: 5 kB\nSwapTotal: 0 kB\nSwapFree: 0 kB\n')
  assert.equal(noSwap.ok, true)
  assert.equal(noSwap.data.swapUsed, 0)
  failed(parsers.parseMeminfo('MemTotal: 10 kB\n'))
  failed(parsers.parseMeminfo('MemTotal: 10 kB\nMemAvailable: 11 kB\n'))
  failed(parsers.parseMeminfo('MemTotal: -1 kB\nMemAvailable: 0 kB\n'))
})

test('parses uptime and load average with bounded numeric/task validation', () => {
  assert.equal(parsers.parseUptime(fixture('uptime-valid.txt')).data.seconds, 12345.67)
  assert.equal(parsers.parseUptime('0\n').ok, true)
  failed(parsers.parseUptime('-1 2\n'))
  failed(parsers.parseUptime('Infinity 2\n'))
  const load = parsers.parseLoadavg(fixture('loadavg-valid.txt'))
  assert.equal(load.data.one, 0.42)
  assert.equal(load.data.five, 1.03)
  assert.equal(load.data.fifteen, 2.5)
  assert.equal(load.data.runningTasks, 3)
  assert.equal(load.data.totalTasks, 456)
  assert.equal(load.data.lastPid, 7890)
  failed(parsers.parseLoadavg('0.1 0.2 0.3 4/3 1\n'))
  failed(parsers.parseLoadavg('0.1 0.2\n'))
  failed(parsers.parseLoadavg('NaN 0.2 0.3 1/2 3\n'))
})

test('parses os-release without executing it and rejects malformed assignments', () => {
  const result = parsers.parseOsRelease(fixture('os-release-valid.txt'))
  assert.equal(result.ok, true)
  assert.equal(result.data.displayName, 'Example Linux 2026.09')
  const escaped = parsers.parseOsRelease('NAME="Example \\${notExecuted}"\nVERSION_ID=1\n')
  assert.equal(escaped.ok, true)
  assert.equal(escaped.data.displayName, 'Example ${notExecuted} 1')
  failed(parsers.parseOsRelease('NAME="Only name"\n'))
  failed(parsers.parseOsRelease('NAME="unterminated\nVERSION_ID=1\n'))
  failed(parsers.parseOsRelease('not-an-assignment\n'))
  failed(parsers.parseOsRelease('NAME="A"\nNAME="B"\nVERSION_ID=1\n'))
})
